/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SellRouteImport } from './routes/sell'
import { Route as RepairRouteImport } from './routes/repair'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StaffPerformanceRouteImport } from './routes/staff.performance'
import { Route as StaffPartsRouteImport } from './routes/staff.parts'
import { Route as StaffJobsRouteImport } from './routes/staff.jobs'
import { Route as StaffGradingRouteImport } from './routes/staff.grading'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as AdminTechniciansRouteImport } from './routes/admin.technicians'
import { Route as AdminSellRequestsRouteImport } from './routes/admin.sell-requests'
import { Route as AdminRepairsRouteImport } from './routes/admin.repairs'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminBranchesRouteImport } from './routes/admin.branches'

const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairRoute = RepairRouteImport.update({
  id: '/repair',
  path: '/repair',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StaffPerformanceRoute = StaffPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => StaffRoute,
} as any)
const StaffPartsRoute = StaffPartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => StaffRoute,
} as any)
const StaffJobsRoute = StaffJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => StaffRoute,
} as any)
const StaffGradingRoute = StaffGradingRouteImport.update({
  id: '/grading',
  path: '/grading',
  getParentRoute: () => StaffRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTechniciansRoute = AdminTechniciansRouteImport.update({
  id: '/technicians',
  path: '/technicians',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSellRequestsRoute = AdminSellRequestsRouteImport.update({
  id: '/sell-requests',
  path: '/sell-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRepairsRoute = AdminRepairsRouteImport.update({
  id: '/repairs',
  path: '/repairs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBranchesRoute = AdminBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/catalog': typeof CatalogRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/repair': typeof RepairRoute
  '/sell': typeof SellRoute
  '/signup': typeof SignupRoute
  '/staff': typeof StaffRouteWithChildren
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/repairs': typeof AdminRepairsRoute
  '/admin/sell-requests': typeof AdminSellRequestsRoute
  '/admin/technicians': typeof AdminTechniciansRoute
  '/product/$id': typeof ProductIdRoute
  '/staff/grading': typeof StaffGradingRoute
  '/staff/jobs': typeof StaffJobsRoute
  '/staff/parts': typeof StaffPartsRoute
  '/staff/performance': typeof StaffPerformanceRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/catalog': typeof CatalogRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/repair': typeof RepairRoute
  '/sell': typeof SellRoute
  '/signup': typeof SignupRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/repairs': typeof AdminRepairsRoute
  '/admin/sell-requests': typeof AdminSellRequestsRoute
  '/admin/technicians': typeof AdminTechniciansRoute
  '/product/$id': typeof ProductIdRoute
  '/staff/grading': typeof StaffGradingRoute
  '/staff/jobs': typeof StaffJobsRoute
  '/staff/parts': typeof StaffPartsRoute
  '/staff/performance': typeof StaffPerformanceRoute
  '/admin': typeof AdminIndexRoute
  '/staff': typeof StaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/catalog': typeof CatalogRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/repair': typeof RepairRoute
  '/sell': typeof SellRoute
  '/signup': typeof SignupRoute
  '/staff': typeof StaffRouteWithChildren
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/repairs': typeof AdminRepairsRoute
  '/admin/sell-requests': typeof AdminSellRequestsRoute
  '/admin/technicians': typeof AdminTechniciansRoute
  '/product/$id': typeof ProductIdRoute
  '/staff/grading': typeof StaffGradingRoute
  '/staff/jobs': typeof StaffJobsRoute
  '/staff/parts': typeof StaffPartsRoute
  '/staff/performance': typeof StaffPerformanceRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/catalog'
    | '/checkout'
    | '/login'
    | '/repair'
    | '/sell'
    | '/signup'
    | '/staff'
    | '/admin/branches'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/repairs'
    | '/admin/sell-requests'
    | '/admin/technicians'
    | '/product/$id'
    | '/staff/grading'
    | '/staff/jobs'
    | '/staff/parts'
    | '/staff/performance'
    | '/admin/'
    | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/catalog'
    | '/checkout'
    | '/login'
    | '/repair'
    | '/sell'
    | '/signup'
    | '/admin/branches'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/repairs'
    | '/admin/sell-requests'
    | '/admin/technicians'
    | '/product/$id'
    | '/staff/grading'
    | '/staff/jobs'
    | '/staff/parts'
    | '/staff/performance'
    | '/admin'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/catalog'
    | '/checkout'
    | '/login'
    | '/repair'
    | '/sell'
    | '/signup'
    | '/staff'
    | '/admin/branches'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/repairs'
    | '/admin/sell-requests'
    | '/admin/technicians'
    | '/product/$id'
    | '/staff/grading'
    | '/staff/jobs'
    | '/staff/parts'
    | '/staff/performance'
    | '/admin/'
    | '/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  CatalogRoute: typeof CatalogRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  RepairRoute: typeof RepairRoute
  SellRoute: typeof SellRoute
  SignupRoute: typeof SignupRoute
  StaffRoute: typeof StaffRouteWithChildren
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repair': {
      id: '/repair'
      path: '/repair'
      fullPath: '/repair'
      preLoaderRoute: typeof RepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/staff/performance': {
      id: '/staff/performance'
      path: '/performance'
      fullPath: '/staff/performance'
      preLoaderRoute: typeof StaffPerformanceRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/parts': {
      id: '/staff/parts'
      path: '/parts'
      fullPath: '/staff/parts'
      preLoaderRoute: typeof StaffPartsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/jobs': {
      id: '/staff/jobs'
      path: '/jobs'
      fullPath: '/staff/jobs'
      preLoaderRoute: typeof StaffJobsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/grading': {
      id: '/staff/grading'
      path: '/grading'
      fullPath: '/staff/grading'
      preLoaderRoute: typeof StaffGradingRouteImport
      parentRoute: typeof StaffRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/technicians': {
      id: '/admin/technicians'
      path: '/technicians'
      fullPath: '/admin/technicians'
      preLoaderRoute: typeof AdminTechniciansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sell-requests': {
      id: '/admin/sell-requests'
      path: '/sell-requests'
      fullPath: '/admin/sell-requests'
      preLoaderRoute: typeof AdminSellRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/repairs': {
      id: '/admin/repairs'
      path: '/repairs'
      fullPath: '/admin/repairs'
      preLoaderRoute: typeof AdminRepairsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/branches': {
      id: '/admin/branches'
      path: '/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AdminBranchesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBranchesRoute: typeof AdminBranchesRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminRepairsRoute: typeof AdminRepairsRoute
  AdminSellRequestsRoute: typeof AdminSellRequestsRoute
  AdminTechniciansRoute: typeof AdminTechniciansRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBranchesRoute: AdminBranchesRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminRepairsRoute: AdminRepairsRoute,
  AdminSellRequestsRoute: AdminSellRequestsRoute,
  AdminTechniciansRoute: AdminTechniciansRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StaffRouteChildren {
  StaffGradingRoute: typeof StaffGradingRoute
  StaffJobsRoute: typeof StaffJobsRoute
  StaffPartsRoute: typeof StaffPartsRoute
  StaffPerformanceRoute: typeof StaffPerformanceRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffGradingRoute: StaffGradingRoute,
  StaffJobsRoute: StaffJobsRoute,
  StaffPartsRoute: StaffPartsRoute,
  StaffPerformanceRoute: StaffPerformanceRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  CatalogRoute: CatalogRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  RepairRoute: RepairRoute,
  SellRoute: SellRoute,
  SignupRoute: SignupRoute,
  StaffRoute: StaffRouteWithChildren,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
